name: "Lint for Firefox"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: "Lint for Firefox"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install web-ext
        run: npm install --global web-ext

      - name: Remove unnecessary files
        run: rm -rf .github/ .gitignore .git/ .idea/ docs/ manifest.json README.md
      - name: Switch to v2 for manifest
        run: mv manifest-v2.json manifest.json

      - name: Run lint
        run: web-ext lint
