name: "Lint for Firefox"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: "Lint for Firefox"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Remove unnecessary files
        run: rm -rf .github/ .gitignore .git/ .idea/ docs/ manifest.json README.md
      - name: Switch to v2 for manifest
        run: mv manifest-v2.json manifest.json

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: src
          channel: listed
