name: Releaser

on:
  release:
    types:
      - released

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  update-version:
    name: Update version name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update version in manifest
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.event.release.tag_name }}\"/" manifest.json
      - name: Commit version.properties
        id: commit_version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated version
          file_pattern: 'manifest.json'
          branch: master

  release-chrome:
    name: Release for Chrome
    runs-on: ubuntu-latest
    needs: [update-version]
    if: ${{ false && always() && !cancelled() && needs.update-version.result == 'success' }}
    # api usage reference:
    # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
    # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
    env:
      # you can optionally specify extension ID here, we do this so that
      # all of our environments (dev, staging, prod) have a consistent ID
      # we can reference. Otherwise the extension ID is autogenerated.
      EXTENSION_ID: npfnhbnfidlfkkoafboojlabnjaoldip
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Remove unnecessary files
        run: rm -rf .github/ .gitignore .git/ .idea/ docs/ README.md
      - name: Update version in manifest
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.event.release.tag_name }}\"/" manifest.json
      - name: Create ZIP
        run: zip -r ${{ github.event.release.tag_name }}-chrome.zip .

      - name: Upload Chrome Extension
        uses: wdzeng/chrome-extension@v1
        with:
          extension-id: ${{ env.EXTENSION_ID }}
          zip-path: ${{ github.event.release.tag_name }}-chrome.zip
          client-id: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}

  release-firefox-store:
    name: Release for Firefox in Addons Store
    runs-on: ubuntu-latest
    needs: [update-version]
    if: ${{ always() && !cancelled() && needs.update-version.result == 'success' }}
    env:
      ADDON_GUID: "{279d1741-5957-4326-99d1-9b9b4e519e7a}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Update version in manifest
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.event.release.tag_name }}\"/" manifest.json

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Remove unnecessary files
        run: rm -rf .github/ .gitignore .git/ .idea/ docs/ README.md
      - name: Switch to v2 for manifest
        run: |
          sed -i "s/\"manifest_version\": 3/\"manifest_version\": 2/" manifest.json

      - name: Package release
        run: zip -r upv_repowered-${{ github.event.release.tag_name }}.zip .

      - uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: ${{ env.ADDON_GUID }}
          xpi-path: upv_repowered-${{ github.event.release.tag_name }}.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
  release-firefox-github:
    name: Release for Firefox in Github Releases
    runs-on: ubuntu-latest
    needs: [update-version]
    if: ${{ always() && !cancelled() && needs.update-version.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Update version in manifest
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.event.release.tag_name }}\"/" manifest.json

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Remove unnecessary files
        run: rm -rf .github/ .gitignore .git/ .idea/ docs/ README.md
      - name: Switch to v2 for manifest
        run: |
          sed -i "s/\"manifest_version\": 3/\"manifest_version\": 2/" manifest.json

      - name: Sign release as unlisted
        run: web-ext sign --api-key="${{ secrets.FIREFOX_JWT_ISSUER }}" --api-secret="${{ secrets.FIREFOX_JWT_SECRET }}" --channel unlisted

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: web-ext-artifacts/upv_repowered-${{ github.event.release.tag_name }}.xpi
          asset_name: firefox-${{ github.event.release.tag_name }}.xpi
          tag: ${{ github.ref }}
          overwrite: true
