name: Releaser

on:
  push:
    tags:
      - v*.*.**

jobs:
  build:
    name: Compress and Release extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create ZIP
        run: zip -r extension-${{ env.RELEASE_VERSION }}.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-${{ github.sha }}
          path: extension-${{ env.RELEASE_VERSION }}.zip
  release-chrome:
    name: Release for Chrome
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    # api usage reference:
    # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
    # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
    env:
      # you can optionally specify extension ID here, we do this so that
      # all of our environments (dev, staging, prod) have a consistent ID
      # we can reference. Otherwise the extension ID is autogenerated.
      EXTENSION_ID: npfnhbnfidlfkkoafboojlabnjaoldip
    steps:
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: "16.10"
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-${{ github.sha }}

      - name: Install webstore cli
        run: npm install -g chrome-webstore-upload-cli

      - name: Upload step
        run: chrome-webstore-upload upload --source extension-${{ env.RELEASE_VERSION }}.zip --extension-id ${{ env.EXTENSION_ID }} --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
  release-firefox:
    name: Release for Firefox
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    env:
      ADDON_GUID: 279d1741-5957-4326-99d1-9b9b4e519e7a
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-${{ github.sha }}
      - uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: ${{ env.ADDON_GUID }}
          xpi-path: extension-${{ env.RELEASE_VERSION }}.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
